### ISSUE TITLE
Next time don't upload personal business on GitHub 

### ISSUE THREAD

**Issue by Temian1** [chinnyfity/iContestPro#1]

**Comment by chinnyfity** [comment]
Thank you sir, i actually forgot to make it private, i made other company projects private but i didnt see this one, thanks for the correction
    On Friday, December 2, 2022 at 01:16:54 PM GMT+1, Temian1 ***@***.***> wrote:  
 
 


I hope you learn your lesson

**Comment by Temian1** [comment]
Uwc
